# Generated by Django 6.0.2 on 2026-02-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_ticket'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('row', 'seat', 'movie_session'), name='unique_movie_session_row_seat'),
        ),
    ]
